name: Build Android AAB (One-Shot)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses + install build-tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Install deps (Bubblewrap + expect)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y expect
          npm i -g @bubblewrap/cli

      - name: Generate signing key
        run: |
          keytool -genkeypair -v \
            -keystore android.keystore \
            -storepass changeit123 \
            -keypass changeit123 \
            -alias njpwa \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=NJ Pour Digital, OU=Apps, O=NJ Pour Digital, L=East Brunswick, ST=NJ, C=US"

      - name: Non-interactive Bubblewrap init (uses your live manifest)
        shell: bash
        run: |
          # RAW URL to your web manifest:
          MANIFEST_URL="https://raw.githubusercontent.com/pnnondual/njpourdigital-clean/main/manifest.webmanifest"

          /usr/bin/expect << 'EOF'
          set timeout -1
          spawn bubblewrap init --manifest https://raw.githubusercontent.com/pnnondual/njpourdigital-clean/main/manifest.webmanifest
          # choose theme "Simple (just the right amount of UI)" → option 2
          send "2\r"
          # notifications → No
          send "n\r"
          # notification delegation → No
          send "n\r"
          # accept sane defaults for any remaining prompts
          for {set i 0} {$i < 20} {incr i} { send "\r" }
          expect eof
          EOF

          test -f android/app/build.gradle || { echo "android project not created"; exit 1; }

      - name: Patch Gradle (normalize notification flags)
        run: |
          sed -i -E 's/enableNotifications[[:space:]]*[:=][[:space:]]*;?/enableNotifications false/g' android/app/build.gradle || true
          sed -i -E 's/enableNotificationDelegation[[:space:]]*[:=][[:space:]]*;?/enableNotificationDelegation false/g' android/app/build.gradle || true
          sed -i -E 's/enableNotifications[[:space:]]*$/enableNotifications false/g' android/app/build.gradle || true
          sed -i -E 's/enableNotificationDelegation[[:space:]]*$/enableNotificationDelegation false/g' android/app/build.gradle || true
          echo "---- build.gradle lines ----"
          grep -n 'enableNot' android/app/build.gradle || true

      - name: Build AAB (no daemon, more memory)
        working-directory: android
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2g -Dorg.gradle.daemon=false -Dorg.gradle.console=plain
        run: |
          chmod +x ./gradlew || true
          ./gradlew bundleRelease --stacktrace --warning-mode=all --no-daemon

      - name: Show SHA-256 for assetlinks.json
        run: keytool -list -v -keystore android.keystore -alias njpwa -storepass changeit123 | grep SHA256 || true

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/bundle/release/app-release.aab
